### ISSUE TITLE
tests are failing ?

### ISSUE THREAD

**Issue by parmentelat** [Sm00thix/IKPLS#11]
I have tried to run the provided tests on my macbook pro

as touched on in #10 I had to guess my way a little, and here's what I did

```
pip install -e .
pip install pandas pytest
pytest
```

the outcome was

```
=================== 14 failed, 12 passed, 2010 warnings in 1196.90s (0:19:56) ====================
```

so I reckon, there has to be something wrong here

can you please shed light on:
- quite generally, is the test suite expected to pass ? on any hardware ?
- and more specifically, did I prepare things the right way or not ?
- is this result intended because of my hardware ? 

thanks in advance

**Comment by Sm00thix** [comment]
Hi @parmentelat. Thank you for your comments and questions. I will try to answer them all as quickly as possible.

Regarding the test suite:

Most of the tests are related to equality comparisons of internal PLS matrices and prediction results. Due to the different algorithms used, numerical differences are expected to occur. Empirically, I have found these numerical differences also depend on the Python version and hardware executing them. Thus, if you have a different Mac than the one used by GitHub actions, it is possible that some of the tests may fail due to this.

However, I suspect that it is much more likely that you have not enforced JAX to use float64 and so it will instead use float32. Using float32 is devastating for the numerical precision.


Please ensure that you are using 64-bit floats in JAX. JAX enforces float32 by default.

This can be overcome by setting the environment variable JAX_ENABLE_X64 to True. This is written in the README.rst. A link to the official JAX documentation explaining the functionality: [JAX documentation](https://github.com/google/jax#current-gotchas).

**Comment by parmentelat** [comment]
you're right, I had not set `JAX_ENABLE_X64`, and it is mentioned in the `README.rst` indeed 

and I had read that at some point, except that at the time where I triggered the tests I was reading `CONTRIBUTING.rst` where this is no longer mentioned, 
I had also taken a look at the github actions, but was looking in the wrong place in `test/action.yml` and failed to spot it in `workflows/workflow.yml`
botom line is, I screwed it up :)

I would argue this is error-prone, and would simply suggest for the test to set that variable, since it is a mandatory requirement !

with this in place I do get 100% pass this time :)

```
diff --git a/tests/test_ikpls.py b/tests/test_ikpls.py
index f01e07a..5a5c20e 100644
--- a/tests/test_ikpls.py
+++ b/tests/test_ikpls.py
@@ -15,6 +15,8 @@ from ikpls.numpy_ikpls import PLS as NpPLS

 from . import load_data

+jax.config.update("jax_enable_x64", True)
+

 class TestClass:
     csv = load_data.load_csv()
```

**Comment by Sm00thix** [comment]
Hi @parmentelat 

Thank you for getting back so quickly. I agree that setting the variable directly in the test is the best way to handle the issue of using float64 for JAX. I will incorporate your suggestion.
