### ISSUE TITLE
Changes to paper.md introduction and first section in README

### ISSUE THREAD

**Issue by Sm00thix** [Sm00thix/IKPLS#29]
Quoting @basileMarchand from the [review at JOSS](https://github.com/openjournals/joss-reviews/issues/6533):

In the JOSS paper, it would be good in my opinion to have a more "simplified" introduction in the summary so that a less experienced reader can easily understand what need the package is addressing. Also, the first paragraph of the README (which is also the first paragraph of the documentation) should be made more engaging to catch the attention of readers who might be searching without really knowing what they need. This would help attract more users and build a more diverse community.

**Comment by Sm00thix** [comment]
Hi @basileMarchand,

I have done my best to implement the requested changes.
Please, let me know what you think.

**Comment by basileMarchand** [comment]
Hi  @Sm00thix,

thank you for the work on rewriting the introduction. I think it makes the paper more engaging now because it's more accessible to people who are not specialists (they can understand what they just came across). I believe that even for you, for the dissemination of your package, this will help reach more people. Just one last suggestion, I think you could take the first 2-3 sentences of the JOSS paper summary and integrate them directly into the README, in the first section, so that anyone who comes across the IKPLS documentation or repository can immediately understand what they have found.

**Comment by Sm00thix** [comment]
Hi @basileMarchand!

Thank you for your suggestions and aid in improving the reach of `ikpls`. I have incorporated your last suggestion in https://github.com/Sm00thix/IKPLS/commit/36b10aedb42de483d89c3b9adf24723840401439. :-)

**Comment by Sm00thix** [comment]
Hi @basileMarchand,

Thank you! I agree. I will close this issue :-)
